### ISSUE TITLE
kubernetes core app failed to start

### ISSUE THREAD

**Issue by sneerin** [WhatsApp/WhatsApp-Business-API-Setup-Scripts#17]
App fails to start with no specific explanation of why exactly it failed. permissions, networks or something else, I used completely default configs, tried on two different Kubernetes distributions. 

```DB connection option: 
ls: cannot access 'wa-service.log.*': No such file or directory
ls: cannot access 'wa-service.INFO': No such file or directory
sed: -e expression #1, char 0: no previous regular expression

No logs to move
starting normal service from container script
AppPropertiesPrivate::defaultTcpListenAddress_ "any"
AppPropertiesPrivate::multiConnectEnabled_ true
I0115 00:15:02.141500    15 main.cpp:36] ---- FieldStats initialization ---- req_id=Main
I0115 00:15:02.142014    15 fieldstats.cpp:170] FIELDSTATS: wam file is missing req_id=Main
I0115 00:15:02.142508    15 fieldstats.cpp:170] FIELDSTATS: initialized with new wam file req_id=Main
I0115 00:15:02.147759    15 util.cpp:2967] Calling Get Orchestration req_id=Main
I0115 00:15:02.147799    15 util.cpp:2986] Calling Get TemplateVersion req_id=Main
I0115 00:15:02.148895    16 apiendpointmanager.cpp:166] Endpoint "healthcheck" is listening on address "0.0.0.0" port 6253 req_id=Main
I0115 00:15:02.149866    17 apiendpointmanager.cpp:166] Endpoint "control" is listening on address "0.0.0.0" port 6252 req_id=Main
I0115 00:15:02.149940    15 main.cpp:41] ---- ConfigStore initialization ---- req_id=Main
I0115 00:15:02.159400    15 dbsettings.cpp:103] Changed default database engine from "SQLITE" to "MYSQL" req_id=Main
I0115 00:15:02.161686    15 datastore.cpp:670] "create_configStore_139985107619456" connectOption: "MYSQL_OPT_RECONNECT=1;MYSQL_OPT_CONNECT_TIMEOUT=15;MYSQL_OPT_READ_TIMEOUT=30;MYSQL_OPT_WRITE_TIMEOUT=30" req_id=Main
I0115 00:15:02.190256    15 datastore.cpp:94] Created database "configStore" req_id=Main
I0115 00:15:02.190462    15 datastore.cpp:670] "configStore" connectOption: "MYSQL_OPT_RECONNECT=1;MYSQL_OPT_CONNECT_TIMEOUT=15;MYSQL_OPT_READ_TIMEOUT=30;MYSQL_OPT_WRITE_TIMEOUT=30" req_id=Main
I0115 00:15:02.217798    15 datastore.cpp:347] Set sql_mode to "NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ZERO_DATE,NO_AUTO_CREATE_USER,NO_ZERO_IN_DATE" req_id=Main
I0115 00:15:02.218341    15 configstore.cpp:546] Creating cluster info req_id=Main
I0115 00:15:02.218489    15 configstore.cpp:1064] App settings does not exist req_id=Main
I0115 00:15:02.218602    15 configstore.cpp:857] Creating cluster_info table req_id=Main
I0115 00:15:02.219434    15 configstore.cpp:870] cluster_info table created req_id=Main
I0115 00:15:02.220360    15 clusterstore.cpp:55] ClusterStore::ClusterStore() req_id=Main
I0115 00:15:02.220391    15 slavenode.cpp:9] CoreAppNode::CoreAppNode( "multi-instance coreapp" ClusterState::Type(NORMAL)  ) req_id=Main
I0115 00:15:02.220454    15 datastore.cpp:670] "create_clusterStore_139985107619456" connectOption: "MYSQL_OPT_RECONNECT=1;MYSQL_OPT_CONNECT_TIMEOUT=15;MYSQL_OPT_READ_TIMEOUT=30;MYSQL_OPT_WRITE_TIMEOUT=30" req_id=Main
I0115 00:15:02.248736    15 datastore.cpp:94] Created database "clusterStore" req_id=Main
I0115 00:15:02.249078    15 datastore.cpp:670] "clusterStore" connectOption: "MYSQL_OPT_RECONNECT=1;MYSQL_OPT_CONNECT_TIMEOUT=15;MYSQL_OPT_READ_TIMEOUT=30;MYSQL_OPT_WRITE_TIMEOUT=30" req_id=Main
I0115 00:15:02.275458    15 datastore.cpp:347] Set sql_mode to "NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ZERO_DATE,NO_AUTO_CREATE_USER,NO_ZERO_IN_DATE" req_id=Main
I0115 00:15:02.276626    15 clusterstore.cpp:100] cluster database opened req_id=Main
I0115 00:15:02.276661    15 clusterstore.cpp:957] Creating ClusterStore root tables req_id=Main
I0115 00:15:02.278141    15 clusterstore.cpp:1095] Register self to nodes table req_id=Main
I0115 00:15:02.282073    15 clusterstore.cpp:1384] LeaseManager::LeaseManager() req_id=Main
I0115 00:15:02.282209    15 clusterstore.cpp:1116] Get cluster info req_id=Main
I0115 00:15:02.282321    18 clusterstore.cpp:1395] LeaseManager::start() req_id=LeaseManager
W0115 00:15:02.283293    15 clusterstore.cpp:157] Cluster is under ClusterState::Type(UPGRADE) state at ("10.12.20.150":"6250,6251,6252,6253",0) exit! req_id=Main
W0115 00:15:02.283390    15 onpremise_clustermanager.cpp:103] Unable to initialize cluster store req_id=Main
I0115 00:15:02.283426    15 configstore.cpp:599] Failed to initialize cluster manager, will retry after 1000 ms req_id=Main
I0115 00:15:03.283586    15 clusterstore.cpp:1116] Get cluster info req_id=Main
W0115 00:15:03.285792    15 clusterstore.cpp:157] Cluster is under ClusterState::Type(UPGRADE) state at ("10.12.20.150":"6250,6251,6252,6253",0) exit! req_id=Main
W0115 00:15:03.285924    15 onpremise_clustermanager.cpp:103] Unable to initialize cluster store req_id=Main
I0115 00:15:03.285977    15 configstore.cpp:599] Failed to initialize cluster manager, will retry after 2000 ms req_id=Main
I0115 00:15:05.286195    15 clusterstore.cpp:1116] Get cluster info req_id=Main
W0115 00:15:05.287765    15 clusterstore.cpp:157] Cluster is under ClusterState::Type(UPGRADE) state at ("10.12.20.150":"6250,6251,6252,6253",0) exit! req_id=Main
W0115 00:15:05.287859    15 onpremise_clustermanager.cpp:103] Unable to initialize cluster store req_id=Main
I0115 00:15:05.287937    15 configstore.cpp:599] Failed to initialize cluster manager, will retry after 4000 ms req_id=Main
I0115 00:15:09.288110    15 clusterstore.cpp:1116] Get cluster info req_id=Main
W0115 00:15:09.289561    15 clusterstore.cpp:157] Cluster is under ClusterState::Type(UPGRADE) state at ("10.12.20.150":"6250,6251,6252,6253",0) exit! req_id=Main
W0115 00:15:09.289645    15 onpremise_clustermanager.cpp:103] Unable to initialize cluster store req_id=Main
I0115 00:15:09.289670    15 configstore.cpp:599] Failed to initialize cluster manager, will retry after 8000 ms req_id=Main
I0115 00:15:17.289829    15 clusterstore.cpp:1116] Get cluster info req_id=Main
W0115 00:15:17.292439    15 clusterstore.cpp:157] Cluster is under ClusterState::Type(UPGRADE) state at ("10.12.20.150":"6250,6251,6252,6253",0) exit! req_id=Main
W0115 00:15:17.292665    15 onpremise_clustermanager.cpp:103] Unable to initialize cluster store req_id=Main
I0115 00:15:17.292867    15 configstore.cpp:599] Failed to initialize cluster manager, will retry after 16000 ms req_id=Main
I0115 00:15:24.003279    16 apiendpointmanager.cpp:245] Processing incoming TCP socket connection on port 6253 from QHostAddress("::ffff:10.12.20.150") req_id=healthcheckEndpoint
I0115 00:15:24.003516    16 apiendpointmanager.cpp:347] API submittal to "healthcheck" has version 1 and size 382 req_id=2abd62ab9c8f433a9ebdf116a4ddde40
I0115 00:15:24.003952    16 apiendpointmanager.cpp:541] "heartbeat" API submittal to "healthcheck" handled in 0 ms req_id=2abd62ab9c8f433a9ebdf116a4ddde40
I0115 00:15:29.004329    16 apiendpointmanager.cpp:245] Processing incoming TCP socket connection on port 6253 from QHostAddress("::ffff:10.12.20.150") req_id=healthcheckEndpoint
I0115 00:15:29.004426    16 apiendpointmanager.cpp:347] API submittal to "healthcheck" has version 1 and size 382 req_id=962026d8d2304d0cb27c37f6fc5be2a0
I0115 00:15:29.004810    16 apiendpointmanager.cpp:541] "heartbeat" API submittal to "healthcheck" handled in 0 ms req_id=962026d8d2304d0cb27c37f6fc5be2a0
I0115 00:15:33.293115    15 clusterstore.cpp:1116] Get cluster info req_id=Main
W0115 00:15:33.296357    15 clusterstore.cpp:157] Cluster is under ClusterState::Type(UPGRADE) state at ("10.12.20.150":"6250,6251,6252,6253",0) exit! req_id=Main
W0115 00:15:33.314177    15 onpremise_clustermanager.cpp:103] Unable to initialize cluster store req_id=Main
I0115 00:15:33.314230    15 configstore.cpp:599] Failed to initialize cluster manager, will retry after 32000 ms req_id=Main
I0115 00:15:34.003326    16 apiendpointmanager.cpp:245] Processing incoming TCP socket connection on port 6253 from QHostAddress("::ffff:10.12.20.150") req_id=healthcheckEndpoint
I0115 00:15:34.003638    16 apiendpointmanager.cpp:347] API submittal to "healthcheck" has version 1 and size 382 req_id=6879630cd700481aa101bbcd6f1e2628
I0115 00:15:34.004247    16 apiendpointmanager.cpp:541] "heartbeat" API submittal to "healthcheck" handled in 1 ms req_id=6879630cd700481aa101bbcd6f1e2628```

**Comment by mengyiyuan** [comment]
Hi,

For specific setup issues, please use the Direct support channel as mentioned in the official docs: https://developers.facebook.com/docs/whatsapp/contact-support

This repo is more for general discussion on these scripts.

Thanks.

**Comment by mustafasayilgan** [comment]
hi @sneerin  @mengyiyuan , I hope you guys see my comment. i am facing the same problem. do you guys know what is the solution?


`No logs to movestarting normal service from container scriptD 2023-02-07 12:12:06.667 UTC 16 D 2023-02-07 12:12:06.667 UTC 16 D 2023-02-07 12:12:06.667 UTC 16 D 2023-02-07 12:12:06.668 UTC 16 main.cpp:38] ---- FieldStats initialization ---- req_id=MainFIELDSTATS: D 2023-02-07 12:12:06.668 UTC 16 fieldstats.cpp:177] wam file is missing req_id=MainFIELDSTATS: D 2023-02-07 12:12:06.670 UTC 16 fieldstats.cpp:177] initialized with new wam file req_id=MainD 2023-02-07 12:12:06.672 UTC 16 util.cpp:936] Calling Get Orchestration req_id=MainD 2023-02-07 12:12:06.672 UTC 16 util.cpp:1004] Calling Get TemplateVersion req_id=MainD 2023-02-07 12:12:06.672 UTC 16 main.cpp:43] ---- ConfigStore initialization ---- req_id=MainD 2023-02-07 12:12:06.672 UTC 16 dbsettings.cpp:75] Database engine is set to  "MYSQL" req_id=MainD 2023-02-07 12:12:06.674 UTC 16 datastore.cpp:758] "create_configStore_140639843464128" connectOption: "MYSQL_OPT_RECONNECT=1;MYSQL_OPT_CONNECT_TIMEOUT=15;MYSQL_OPT_READ_TIMEOUT=30;MYSQL_OPT_WRITE_TIMEOUT=30" req_id=MainD 2023-02-07 12:12:06.683 UTC 16 datastore.cpp:106] Created database "908502421215configStore" req_id=MainD 2023-02-07 12:12:06.683 UTC 16 datastore.cpp:758] "configStore" connectOption: "MYSQL_OPT_RECONNECT=1;MYSQL_OPT_CONNECT_TIMEOUT=15;MYSQL_OPT_READ_TIMEOUT=30;MYSQL_OPT_WRITE_TIMEOUT=30" req_id=MainD 2023-02-07 12:12:06.683 UTC 16 datastore.cpp:162] Initiated DB connection "908502421215configStore"  of engine type "MYSQL" req_id=MainD 2023-02-07 12:12:06.685 UTC 16 datastore.cpp:400] Set the DB connection timeout to:  10  sec req_id=MainI 2023-02-07 12:12:06.688 UTC 16 datastore.cpp:357] Set sql_mode to "NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_AUTO_CREATE_USER,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO" req_id=MainD 2023-02-07 12:12:06.688 UTC 16 configstore.cpp:495] Creating cluster info req_id=MainI 2023-02-07 12:12:06.688 UTC 16 configstore.cpp:1043] App settings does not exist req_id=MainD 2023-02-07 12:12:06.689 UTC 16 configstore.cpp:804] Creating cluster_info table req_id=MainD 2023-02-07 12:12:06.692 UTC 16 configstore.cpp:817] cluster_info table created req_id=MainD 2023-02-07 12:12:06.693 UTC 16 clusterstore.cpp:58] ClusterStore::ClusterStore() req_id=MainD 2023-02-07 12:12:06.693 UTC 16 slavenode.cpp:12] CoreAppNode::CoreAppNode( "multi-instance coreapp" ClusterState::Type::NORMAL  ) req_id=MainD 2023-02-07 12:12:06.693 UTC 16 datastore.cpp:758] "create_clusterStore_140639843464128" connectOption: "MYSQL_OPT_RECONNECT=1;MYSQL_OPT_CONNECT_TIMEOUT=15;MYSQL_OPT_READ_TIMEOUT=30;MYSQL_OPT_WRITE_TIMEOUT=30" req_id=MainD 2023-02-07 12:12:06.698 UTC 16 datastore.cpp:106] Created database "908502421215clusterStore" req_id=MainD 2023-02-07 12:12:06.698 UTC 16 datastore.cpp:758] "clusterStore" connectOption: "MYSQL_OPT_RECONNECT=1;MYSQL_OPT_CONNECT_TIMEOUT=15;MYSQL_OPT_READ_TIMEOUT=30;MYSQL_OPT_WRITE_TIMEOUT=30" req_id=MainD 2023-02-07 12:12:06.699 UTC 16 datastore.cpp:162] Initiated DB connection "908502421215clusterStore"  of engine type "MYSQL" req_id=MainD 2023-02-07 12:12:06.701 UTC 16 datastore.cpp:400] Set the DB connection timeout to:  10  sec req_id=MainI 2023-02-07 12:12:06.704 UTC 16 datastore.cpp:357] Set sql_mode to "NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_AUTO_CREATE_USER,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO" req_id=MainD 2023-02-07 12:12:06.704 UTC 16 clusterstore.cpp:103] cluster database opened req_id=MainD 2023-02-07 12:12:06.704 UTC 16 clusterstore.cpp:1018] Creating ClusterStore root tables req_id=MainD 2023-02-07 12:12:06.706 UTC 16 clusterstore.cpp:1131] Register self to nodes table req_id=MainD 2023-02-07 12:12:06.712 UTC 16 clusterstore.cpp:1448] LeaseManager::LeaseManager() req_id=MainD 2023-02-07 12:12:06.713 UTC 16 clusterstore.cpp:1155] Get cluster info req_id=MainD 2023-02-07 12:12:06.713 UTC 17 clusterstore.cpp:1457] LeaseManager::start() req_id=LeaseManagerW 2023-02-07 12:12:06.713 UTC 16 clusterstore.cpp:164] Cluster is under ClusterState::Type::UPGRADE state at ("10.112.0.149":"6250,6251,6252,6253",0) exit! req_id=MainW 2023-02-07 12:12:06.714 UTC 16 onpremise_clustermanager.cpp:128] Unable to initialize cluster store req_id=MainD 2023-02-07 12:12:06.714 UTC 16 configstore.cpp:548] Failed to initialize cluster manager, will retry after 1000 ms req_id=Main`

**Comment by Mahlyjan** [comment]
I'm facing the exact same issue. 
@mustafasayilgan @sneerin 
Would anyone know how to resolve the issue?

**Comment by mustafasayilgan** [comment]
Nope Sorry, İ did not get solution yet /:
