### ISSUE TITLE
app crash: thread timer issue

### ISSUE THREAD

**Issue by sneerin** [WhatsApp/WhatsApp-Business-API-Setup-Scripts#18]
``` I0115 00:51:54.276895    15 datastore.cpp:1015] Removed DB connection "clusterStore" req_id=Main
W0115 00:51:54.276974    15 none:0] QObject::~QObject: Timers cannot be stopped from another thread req_id=Main```

**Comment by mengyiyuan** [comment]
Hi,

For specific setup issues, please use the Direct support channel as mentioned in the official docs: https://developers.facebook.com/docs/whatsapp/contact-support

This repo is more for general discussion on these scripts.

Thanks.
