### ISSUE TITLE
Missing a whatsapp server IP in your zip archive

### ISSUE THREAD

**Issue by clebig** [WhatsApp/WhatsApp-Business-API-Setup-Scripts#2]
Dear Whatsapp team,

Could you add 179.60.192.48/32 and 157.240.21.51/32 to your "List of the WhatsApp server IP addresses and ranges (ZIP)" that you provide here : https://developers.facebook.com/docs/whatsapp/network-debugging.

I can spot these IPs  which seem to be  VOIP gateways or proxies when doing calls (UDP 3478).

see https://github.com/ntop/nDPI/issues/683#issue-425560749

Thank you.

**Comment by thiagocmoraes** [comment]
Let us take a look on this. 

PS: probably Direct Support is a better channel to report that and with closer monitoring. Thanks for reporting!

**Comment by clebig** [comment]
Hi Thiago, 
You are right, unfortunately I don't have a Facebook dev account so I don't have an access to direct support or at least I couldn't find it.

**Comment by mscmartin** [comment]
I need help, urgently! I do not know what else to try! WACORE does not start! Error: "Exit 1"

        Name                       Command               State                  Ports
----------------------------------------------------------------------------------------------------
installation_db_1       docker-entrypoint.sh mysqld      Up       0.0.0.0:33060->3306/tcp, 33060/tcp
installation_wacore_1   /opt/whatsapp/bin/wait_on_ ...   Exit 1
installation_waweb_1    /opt/whatsapp/bin/wait_on_ ...   Up       0.0.0.0:9090->443/tcp, 9090/tcp

**Comment by mengyiyuan** [comment]
@mscmartin, this is not a support channel for WhatsApp Business API. Could you please open a direct support ticket by following the instructions here? https://developers.facebook.com/docs/whatsapp/contact-support

You can also self troubleshoot by using our debugging tool `WADebug`, https://developers.facebook.com/docs/whatsapp/guides/wadebug

Thanks!
