### ISSUE TITLE
coreapp.yaml error on Developer Setup: Multiconnect on Minikube

### ISSUE THREAD

**Issue by cappe89** [WhatsApp/WhatsApp-Business-API-Setup-Scripts#27]
Hi, 
I'm trying to install the latest version 2.27.12 on minikube but at I receive the error below caused by the bad indentation at line 125 - name: COREAPP_HOSTNAME

E:\Kubernetes\wa\installation\kubernetes>kubectl apply -f coreapp.yaml
error: error parsing coreapp.yaml: error converting YAML to JSON: yaml: line 78: did not find expected key

**Comment by mengyiyuan** [comment]
@cappe89 unfortunately we currently don't support Windows systems. Can you try installing it on a Linux based machine?
