### ISSUE TITLE
ERR_CERT_AUTHORITY_INVALID

### ISSUE THREAD

**Issue by jhow2892** [WhatsApp/WhatsApp-Business-API-Setup-Scripts#28]
Good night people! I am now starting to send with the WhatsApp Business API and I am receiving this error ERR_CERT_AUTHORITY_INVALID, it seems to me that the SSL generated inside the docker is not valid, has anyone been through this?

**Comment by mengyiyuan** [comment]
@jhow2892 Can you give more context about when and where you see this error?

**Comment by ybkotak** [comment]
@mengyiyuan - I faced a similar issue. Here's the screenshot for you to see -> https://cl.ly/33f48da2ec5c (Chrome will not let us bypass this at all). Thanks a bunch in advance. @jhow2892 - you got the same error I believe?

**Comment by jhow2892** [comment]
Hello guys, I'm sorry for the delay, I was really working on the implementation of the WhatsApp Business API on our system, @ybkotak  I still couldn't solve this, my problem is not for access, because at that moment we don't see how a serious problem is accessing the browser to be insecure, our biggest difficulty was to consume the API, to get around (temporarily) this, instead of making a post on the URL example: POST https://wabaservice:9090/ we created a service on the host machine where the dockers are installed , with that we make a request in https://localhost:9090 ignoring the SSL certificate, I did it in go, php, python, jquery using the examples that PostMan itself generates, I know this is not a good practice, but it was only solution I have found so far.

Sorry for my English

**Comment by jhow2892** [comment]
@mengyiyuan the @ybkotak portrayed exactly the error that I'm trying to solve.

Sorry for my English

**Comment by mengyiyuan** [comment]
We only used a default self-signed cert for https://localhost:9090 and it should only be used for testing purposes.

You should generate a valid cert and use it for the API endpoint by following the guide at https://developers.facebook.com/docs/whatsapp/api/certificates#upload

Hope this helps!
