### ISSUE TITLE
WA_DB_CONNECTION_IDLE_TIMEOUT what is recommended value?

### ISSUE THREAD

**Issue by Goodsmileduck** [WhatsApp/WhatsApp-Business-API-Setup-Scripts#32]
On https://developers.facebook.com/docs/whatsapp/changelog
I still see 
```
Ability to close idle MYSQL DB connections using WA_DB_CONNECTION_IDLE_TIMEOUT (in seconds)
```

On https://developers.facebook.com/docs/whatsapp/guides/mysql
```
WA_DB_CONNECTION_IDLE_TIMEOUT — By setting this environment variable (in milliseconds) while starting the Coreapp, you can set the idle timeout for your MySQL database. The MySQL server will then close any database connections that are idle for the time set.
```

Meanwhile, in docker-compose config you have value `180000`
https://github.com/WhatsApp/WhatsApp-Business-API-Setup-Scripts/blob/master/installation/db.env#L11

1. So what is a measure for that variable? 
2. What is the recommended value? 
3. Is it different for different app versions?
4. Only for coreapp containers?

https://github.com/WhatsApp/WhatsApp-Business-API-Setup-Scripts/blob/0a932af7ef166294a7ca8f816fbd2f65761f8ad4/installation/kubernetes/db.env#L11

**Comment by mengyiyuan** [comment]
@Goodsmileduck Thanks for reporting the discrepancy in the docs! I believe the value is in milliseconds, so I will file an internal task to fix the Changelog.

To answer your question:
1. The value should be 180000
2. 180000 is what we recommend for high volume throughput, https://developers.facebook.com/docs/whatsapp/guides/high-throughput

For 3,4, let me check with the team to confirm. Will reply once I have the answer.

**Comment by mengyiyuan** [comment]
@Goodsmileduck 

The variable should be set with the measure of milliseconds. Some context about this complexity:
Before v2.27.11, which includes v2.27.8 where you quoted the Changelog from, there was a bug in this variable that we later fixed.

From v2.27.11 onwards, you should set the value to be milliseconds to have the correct behavior.

For high throughput, we currently recommend to set it as 180000 (180s) as documented https://developers.facebook.com/docs/whatsapp/guides/high-throughput.

Currently this variable is only supported by coreapps.

**Comment by Goodsmileduck** [comment]
So for v2.27.8 we should set it to `180`
After v2.27.11 need to set `180000`
right?

**Comment by mengyiyuan** [comment]
> So for v2.27.8 we should set it to `180`
> After v2.27.11 need to set `180000`
> right?

My understanding is that for versions before v2.27.11 (not inclusive), the value will be misinterpreted by one of the DB modules we used (which was the bug) as milliseconds and interpreted as seconds in all other modules, the behavior may be unexpected. 
You don't have to set this value if you have a particular reason (seeing related errors) or I suggest upgrading to v2.27.11 or later.

**Comment by Goodsmileduck** [comment]
Got it. Thank you for clarify!

**Comment by elovin** [comment]
Hi @mengyiyuan is this still only supported when using MySQL or can we use this env variable also with PostgreSQL ?

And if that is the case, can we use something like `idle_in_transaction_session_timeout` from the database side to close the connection of transactions which get stuck ?
