### ISSUE TITLE
Observability - metrics endpoint with bearertoken and expire date

### ISSUE THREAD

**Issue by s4rd1nh4** [WhatsApp/WhatsApp-Business-API-Setup-Scripts#33]
I'm using my own Prometheus to scrape the metrics on the endpoints / metrics? Prometheus and / v1 / stats? Prometheus. Because the token expires every 7 days I have problems analyzing the environment, is there any way around this?

**Comment by mengyiyuan** [comment]
@s4rd1nh4 Currently there's no workaround for this, but we are working on making monitoring tokens with longer expiry duration like we do for the health endpoint. Hopefully it will be included as a new release soon.

Stay tuned on the Changelog. https://developers.facebook.com/docs/whatsapp/changelog
