### ISSUE TITLE
Unable to initialize whatsapp-coreapp cluster 

### ISSUE THREAD

**Issue by anup1384** [WhatsApp/WhatsApp-Business-API-Setup-Scripts#36]
I'm hosting WhatsApp-Business-API setup on AWS Eks Kubernetes and getting below error.

Error-
Unable to initialize cluster store req_id=Main
I0607 11:02:25.276165    15 configstore.cpp:678] Failed to initialize cluster manager, will retry after 8000 ms req_id=Main
I0607 11:02:27.617393    16 apiendpointmanager.cpp:271] Processing incoming TCP socket connection on port 6253 from QHostAddress("::ffff:10.60.17.200") req_id=healthcheckEndpoint

version -v2.27.12

**Comment by mengyiyuan** [comment]
@anup1384 For issues with a specific setup, please use the official support channel and attach the full logs (the snippet you attached here doesn't include an error actually, they are information level logs, indicated by the "I" at the beginning of each line, error logs start the row with a "W") to troubleshoot https://developers.facebook.com/docs/whatsapp/contact-support.

This repo is more for general discussions.

Thanks a lot!
