### ISSUE TITLE
Error runs docker-compose command

### ISSUE THREAD

**Issue by arnezt** [WhatsApp/WhatsApp-Business-API-Setup-Scripts#4]
_docker-compose up -d_
ERROR: Couldn't connect to Docker daemon at http+docker://localhost - is it running?
If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.

then I try as the suggestion command:
_sudo WA_API_VERSION=2.23.4 docker-compose up -d_

ERROR: error pulling image configuration: error parsing HTTP 403 response body: invalid character 'F' looking for beginning of value: "Forbidden!"

How to solve this issue? I am running on Peppermint 9 equal to Ubuntu 18.04 LTS

**Comment by mengyiyuan** [comment]
@arnezt, this is not a support channel for WhatsApp Business API. Could you please open a direct support ticket by following the instructions here? https://developers.facebook.com/docs/whatsapp/contact-support

Meanwhile, I googled and found this post on how to install docker/docker-compose on Peppermint 9, hope it helps https://computingforgeeks.com/install-docker-and-docker-compose-on-linux-mint-19/
