### ISSUE TITLE
Message-id

### ISSUE THREAD

**Issue by ahmedalmulki** [WhatsApp/WhatsApp-Business-API-Setup-Scripts#43]
I already installed a new single instance server, but in the DB I can't find the message_id which I get it from webhook or post message response, so how can I know which msg the user replay for? or if I need to let the msg as read it, if I can't find the message-id in the database?

**Comment by mengyiyuan** [comment]
Hi @ahmedalmulki, as you mentioned you would get the message-id in the webhook payload. Any specific reasons why you want to get the IDs from the DB?
