### ISSUE TITLE
Unable to set up WhatsApp Business API

### ISSUE THREAD

**Issue by shanaeiou** [WhatsApp/WhatsApp-Business-API-Setup-Scripts#44]
Hi, 

I am having an issue with my **set up for WhatsApp Business API** using the FB Biz Manager. 

**What I have done so far:** 

- set up an FB Biz Manager account
- Verified my business
- Created a WhatsApp Business account

**The issue:**
I am unable to find 'WhatsApp Accounts' in my Facebook Business Manager settings, I see Instagram Accounts, but no WhatsApp. 

Please do let me know if there are any fixes for this.

Thank you.

**Comment by edmt** [comment]
I'm not totally sure, but I think Facebook is closing this feature for newcomers. They are signaling that in order to use the whatsapp platform, now you must go through its verified partners: https://www.facebook.com/business/partner-directory/search?platforms=whatsapp&solution_type=messaging

**Comment by shanaeiou** [comment]
@edmt Thanks a lot for the feedback. In this case we are a solution provider co. so it may not be suitable to go through on of the partners. Is there another route for this?

**Comment by mengyiyuan** [comment]
@shanaeiou - @edmt is right that the API access is only open to a selective list of partners now. As you mentioned you are a solutions provider, can you reach out to your FB/WA partner manager about this situation? They should be able to get this fixed.

**Comment by shanaeiou** [comment]
@mengyiyuan Thanks a lot for the advice. May I know what you mean by "FB/WA partner manager"?

**Comment by mengyiyuan** [comment]
> @mengyiyuan Thanks a lot for the advice. May I know what you mean by "FB/WA partner manager"?

They are the people from FB/WA who worked with your company and confirmed that your company is an official partner of the WA Business API.

**Comment by shanaeiou** [comment]
@mengyiyuan I have just checked once again, and thankfully the option is now there, meaning this issue has been resolved. Thanks for the assistance.

**Comment by shanaeiou** [comment]
Sorry, @mengyiyuan, I am having an issue in the next step. The documentation at https://developers.facebook.com/docs/whatsapp/api/account#certificate and  https://developers.facebook.com/docs/whatsapp/getting-started mentions that I should be able to view my certificate or do so by accessing 'WhatsApp Manager'. The issue is that these options are not available.

**Comment by renatomjr** [comment]
Hi @shanaeiou. Were you able to proceed with the configuration? The option 'WhatsApp Accounts' appears to me, but several settings mentioned in the documentation do not exist. I can't even get the certificate.

**Comment by shanaeiou** [comment]
Hi @renatomjr , I was able to see the 'WhatsApp Accounts' option after some time. However, I too was not able to access certain parts of the documentation as what you had mentioned.  I opened another issue regarding that since this one was mainly regarding the 'WhatsApp Accounts' option's visibility. This is the link -> #45 . 

I was informed by @fb-matt that, at this time, Facebook are not onboarding any new businesses. He suggested accessing the WhatsApp Business APIs through one of Facebook's official Business Solution Providers (E.g. Twilio, CM.com, etc.). That is the route that I am currently exploring.

**Comment by phyominh** [comment]
@shanaeiou - Sorry to bump this old thread but I'm also having trouble to get the certificate to register for an account to manage the API. I've contacted a few service providers and some reply back asking for more info about my business. Now it's not like I have a real business to begin with but I'd like to play around with this API and test sending messages.

So what happens after the service provider accepted to work with you? Does the certificate for the phone number appear in the Business Manager after that? Sorry this might not be an ideal place to ask about this.

**Comment by fb-matt** [comment]
@phyominh, there is now a [Developer Community Forum](https://developers.facebook.com/community?sort=trending&category=766772797555412) for WhatsApp Business API developers where you can ask such questions. 
The certificate will not appear for you. The certificate is for the business managing your WhatsApp Business API instance to use to register the phone number. 
A [verified business](https://www.facebook.com/business/help/2058515294227817) is required to use the WhatsApp Business API in any capacity so you will not be able to play around with the API unless you meet the requirements. You may find a partner who provides a limited sandbox functionality to play with messaging on WhatsApp but you will be interfacing with the service providers APIs and not directly with the WhatsApp Business API.
