### ISSUE TITLE
No Option for 'WhatsApp Manager' or View Certificate for WhatsApp Business API

### ISSUE THREAD

**Issue by shanaeiou** [WhatsApp/WhatsApp-Business-API-Setup-Scripts#45]
Hi,

I am **unable to view any options** once I have added my WhatsApp Business Account to Facebook Business Manager. According to the Documentation  (https://developers.facebook.com/docs/whatsapp/api/account#certificate) there should be options to open a **"WhatsApp Manager"** menu or **"View Certificate"** or even check **"Account Status"** but I am unable to view any of them. There are no clickable options once I add my number.

This means I am **unable to view the base64-encoded certificate** which is necessary for the next steps of setting up the WhatsApp Business API. I have attached a screenshot of my screen once adding my number.
![Screen](https://user-images.githubusercontent.com/71476534/94099023-8761c780-fe5c-11ea-91b5-84b15c4127e1.JPG)

Please do let me know if there are any fixes for this.

Thanks.

**Comment by fb-matt** [comment]
The WhatsApp Business API and WhatsApp Business App are two different products.
The options that you are unable to view are for the WhatsApp Business API.
From the [Get Started documentation](https://developers.facebook.com/docs/whatsapp/getting-started), the WhatsApp Business API is in limited public preview. If you don't have access to the preview you can get access through a Business Solution Provider. There is a list at the [Facebook Partner Directory](https://www.facebook.com/business/partner-directory/search?platforms=whatsapp&solution_type=messaging).

**Comment by shanaeiou** [comment]
@fb-matt  Thanks for the feedback. Is there any other way to get access to the preview or is it just by filling out this form (https://www.facebook.com/business/m/whatsapp/business-api)?

**Comment by fb-matt** [comment]
@shanaeiou, at this point in time we aren't onboarding any new businesses through that expression of interest form. If you want to message using the WhatsApp Business API you should look at Business Solution Providers to find one that meets your needs.

**Comment by shanaeiou** [comment]
@fb-matt Thank you for the feedback, really appreciate it. Will look into the Business Solution Provider route.

**Comment by abdulqadeerqureshi** [comment]
Any development on this thread or still have to look into the solution provider route?
Thanks!
