### ISSUE TITLE
clock wrong

### ISSUE THREAD

**Issue by taylanguneyaktas** [WhatsApp/WhatsApp-Business-API-Setup-Scripts#50]
Hi everyone,
My OS Version/build : Windows 10 Home Single Language 64-bit (10.0, Build 19042) (19041.vb_release.191206-1406)
Docker systeinfo : https://paste.ubuntu.com/p/W5Nv3DCHms/
Developer Setup: Single Instance ( https://developers.facebook.com/docs/whatsapp/installation/dev-single-instance )
Steps 1 to 5 okay , no problem.

https://127.0.0.1:9090/  "clock wrong"
Screenshot : https://i.ibb.co/kgJkx5f/clock-wrong.png

how do i solve the problem?

**Comment by taylanguneyaktas** [comment]
Solved

**Comment by agriardyan** [comment]
Sorry to post in old thread. In case someone else stumbled in this issue in future.
I solve this by upgrading the whatsapp api version to latest. Turned out the whatsapp api version in Meta's documentation example is outdated.
