### ISSUE TITLE
Sugerencia/Suggestion

### ISSUE THREAD

**Issue by JoseDeJesusDelaCruzTorres10** [WhatsApp/WhatsApp-Business-API-Setup-Scripts#53]
Español:
La Herramienta Web Business está obsoleta, ¿no? Sugiero que la herramienta sea abierta a Open Source y sea la comunidad de la API de WhatsApp Business quien actualice y mantenga esta interfaz gráfica. Solo que WhatsApp libere el código y que en cada actualización se agregue el código modificado al momento de la nueva versión. Esta interfaz puede ser modificada hasta ser casi la app de WhatsApp Business si la comunidad asi lo desea. Tambien sugiero cambiar el logotipo de la API de WhatsApp Business (que es el mismo de WhatsApp) con este logo FANMADE hecho por BSP's como el que adjunto aqui.

English:
The Web Business Tool is outdated, right? I suggest that the tool be open to Open Source and that the WhatsApp Business API community update and maintain this graphical interface. Only that WhatsApp releases the code and that in each update the modified code is added at the time of the new version. This interface can be modified until it is almost the WhatsApp Business app if the community so wishes. I also suggest changing the WhatsApp Business API logo (which is the same as WhatsApp) with this FANMADE logo made by BSP's like the one attached here.

![whatsapp-business-pricing-2](https://user-images.githubusercontent.com/44839891/102300715-0b3ac580-3f1b-11eb-8483-e1d29a93a3aa.jpg)

![Captura de pantalla de 2020-10-19 12-10-58](https://user-images.githubusercontent.com/44839891/102300945-80a69600-3f1b-11eb-9489-ae2724981d22.png)

![apiwhatsappbusiness](https://user-images.githubusercontent.com/44839891/102300681-fd854000-3f1a-11eb-9fc3-d856fa6b2034.png)

**Comment by mengyiyuan** [comment]
Hi @JoseDeJesusDelaCruzTorres10, thanks a lot for your suggestions on the web admin tool!

You are right that the tool is outdated, because we will deprecate it soon due to the high maintenance cost and it blocks some security updates we want to make.

As you mentioned, some partners have built their own management tool using the API, but for now, we don't plan to open source a tool that we cannot actively manage.

Hope it make sense!
