### ISSUE TITLE
Monitoring with Dynatrace

### ISSUE THREAD

**Issue by pablotdv** [WhatsApp/WhatsApp-Business-API-Setup-Scripts#55]
The version of the PHP used by the web app it's no longer supported by dynatrace. 

How can I monitoring the WhatsApp-Business-API-Setup on dynatrace?
https://www.dynatrace.com/support/help/shortlink/support-php#support-matrix

**Comment by ebersonra** [comment]
@pablotdv I asked this same question, because the PHP version used is not supported by Dyna. This was their response on monitoring: 

https://developers.facebook.com/docs/whatsapp/monitoring/instance

I hope I helped. Hugs!
