### ISSUE TITLE
Facebook and WhatsApp Business API

### ISSUE THREAD

**Issue by JoseDeJesusDelaCruzTorres10** [WhatsApp/WhatsApp-Business-API-Setup-Scripts#56]
Hi, I know that Facebook will release a WhatsApp Business API tool on its own platform. I am wondering if there is any way to test the tool or access it currently? I want to see if it is better if Facebook manages my API endpoint or if it remains the same with my own local installation in Docker.

**Comment by fb-matt** [comment]
We intend to begin testing the cloud-hosted API early this year. At this time, there is no way to request joining the beta. We look forward to continuing to share additional product details over the coming months.

Any updates on the WhatsApp Business API platform and how to use it are published in our official documentation at https://developers.facebook.com/docs/whatsapp
