### ISSUE TITLE
Monitoring instance with postgreSQL

### ISSUE THREAD

**Issue by ccakkan** [WhatsApp/WhatsApp-Business-API-Setup-Scripts#58]
Hi,
The samples are with mysqld_exporter, is postgreSQL also supported for monitoring instance?
Thanks!

**Comment by pablotdv** [comment]
I have the same problem.

**Comment by caiokawasaki** [comment]
@ccakkan @pablotdv any news on this?

**Comment by fb-matt** [comment]
Unfortunately we only support MySQL for the monitoring instance.
You could try to find an exporter for PostgreSQL that you could use instead of the MySQL exporter.
