### ISSUE TITLE
I am not able to add any phone number in Whatsapp Manager.

### ISSUE THREAD

**Issue by suisun2015** [WhatsApp/WhatsApp-Business-API-Setup-Scripts#59]
Hi, 
I have a business account and also can open the "Whatsapp Manager" page.  But the challenge is I can't add any phone number in Whatsapp Manager. Here goes the error message.

"The certificate is not available for your business. Only the business solution provider who manages integration with the WhatsApp business platform will be able to download the certificate."

I hit google to find any solutions for this, but there is none, even I am not sure how to make my account as business solution provider. So please let me know how I can add phone numbers and use the Whatsapp business API.
Many thanks!

Adding my account details in snapshot as attachment.

![image](https://user-images.githubusercontent.com/18753299/121559772-dc2c8900-ca51-11eb-95be-0a7cae26d1ec.png)
![image](https://user-images.githubusercontent.com/18753299/121559452-87890e00-ca51-11eb-82be-d98d439d933d.png)

**Comment by alanhhwong** [comment]
Hi there,

You should have been working with a Business Solutions Provider to get access to this WhatsApp Business Account?  They are the ones who will register the account for you (by downloading the certificate).

Can you share with me account details?  You can email me at alanwong@fb.com

**Comment by suisun2015** [comment]
Thanks for your kind reply. But the thing is... we just want to becoming a solution provider. Is there any solution to this?

**Comment by alanhhwong** [comment]
You can apply here: https://www.facebook.com/business/m/whatsapp/business-api

**Comment by abhiram1673** [comment]
i have also facing the same issue can you you help me out

**Comment by manfye** [comment]
why facebook want to make thing so complicated?

**Comment by bhargavweb** [comment]
@manfye With the recent implementation of the cloud API and you want to call the APIs directly from your application, the certificate is not required anymore.  The certificate is required only if you are integrating with third-party service providers like twilio. Learned this the hard way.

This guy has made a good video of how to setup WhatsApp business Cloud API. Hope it is of some help to anyone coming here.
https://www.youtube.com/watch?v=d6lNxP2gadA

**Comment by manfye** [comment]
@bhargavweb thank you, I will go to explore it further

**Comment by Nirbhay468** [comment]
Why I am not able to generate a certificate for verification.
![image](https://user-images.githubusercontent.com/49951989/175696118-956996b2-38b3-4557-9882-62bdb07f4895.png)

**Comment by hacker-prime** [comment]
> You can apply here: https://www.facebook.com/business/m/whatsapp/business-api

I've applied to this and I haven't received an email from them. Why is this so complicated?

**Comment by hacker-prime** [comment]
> Hi, I have a business account and also can open the "Whatsapp Manager" page. But the challenge is I can't add any phone number in Whatsapp Manager. Here goes the error message.
> 
> "The certificate is not available for your business. Only the business solution provider who manages integration with the WhatsApp business platform will be able to download the certificate."
> 
> I hit google to find any solutions for this, but there is none, even I am not sure how to make my account as business solution provider. So please let me know how I can add phone numbers and use the Whatsapp business API. Many thanks!
> 
> Adding my account details in snapshot as attachment.
> 
> ![image](https://user-images.githubusercontent.com/18753299/121559772-dc2c8900-ca51-11eb-95be-0a7cae26d1ec.png) ![image](https://user-images.githubusercontent.com/18753299/121559452-87890e00-ca51-11eb-82be-d98d439d933d.png)

I am experiencing the same thing and for the life of me I don't know what to do.

**Comment by aslamanver** [comment]
Have you fixed ?

**Comment by hostops** [comment]
This is how I overcome this problem. If you have any issues, command will print them.

```
curl -i -X POST https://graph.facebook.com/v16.0/{phone number id}/register -H 'Authorization: Bearer {your token}' -H 'Content-Type: application/json' -d '{ "pin": "{you make up 6 digit pin}", "messaging_product": "whatsapp"}'
```

**Comment by aviderambo** [comment]
> This is how I overcame this problem. If you have any issues, command will print them.
> 
> ```
> curl -i -X POST https://graph.facebook.com/v16.0/{phone number id}/register -H 'Authorization: Bearer {your token}' -H 'Content-Type: application/json' -d '{ "pin": "{you make up 6 digit pin}", "messaging_product": "whatsapp"}'
> ```
> 
> Maybe this link will be useful if you are building simple whatsapp integration: https://developers.facebook.com/docs/whatsapp/cloud-api/get-started-for-bsps#subscribe-waba

Thanks man. If anyone wondering where to find the phone number id, it's in one of facebook request payloads in the "Getting started" section.

**Comment by tyoc213** [comment]
If the business account had been working with a BSP, but now migrated to cloud API so there is no more intermediary why the business cant get the base64 certificate directly and expects this to be done by a BSP?


(also pinged @alanhhwong by mail)

**Comment by cbw-lsalita** [comment]
same issue, Meta is blocking the certificate code, already signed up with WA Business Platform... still no response....

**Comment by thelinuxkid** [comment]
> This is how I overcame this problem. If you have any issues, command will print them.
> 
> ```
> curl -i -X POST https://graph.facebook.com/v16.0/{phone number id}/register -H 'Authorization: Bearer {your token}' -H 'Content-Type: application/json' -d '{ "pin": "{you make up 6 digit pin}", "messaging_product": "whatsapp"}'
> ```
> 
> Maybe this link will be useful if you are building simple whatsapp integration: https://developers.facebook.com/docs/whatsapp/cloud-api/get-started-for-bsps#subscribe-waba

This worked. Thanks!! If you turn off 2FA then follow this to turn it on again, the display name on the phone number will changed to whatever attempted to change it to without having to download any certificates.

**Comment by RyzorBent** [comment]
> > This is how I overcame this problem. If you have any issues, command will print them.
> > ```
> > curl -i -X POST https://graph.facebook.com/v16.0/{phone number id}/register -H 'Authorization: Bearer {your token}' -H 'Content-Type: application/json' -d '{ "pin": "{you make up 6 digit pin}", "messaging_product": "whatsapp"}'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Maybe this link will be useful if you are building simple whatsapp integration: https://developers.facebook.com/docs/whatsapp/cloud-api/get-started-for-bsps#subscribe-waba
> 
> This worked. Thanks!! If you turn off 2FA then follow this to turn it on again, the display name on the phone number will be changed to whatever you attempted to change it to without having to download any certificates.

This was very helpful, disabling the 2FA did the trick!!

**Comment by ataknakbulut** [comment]
> This is how I overcame this problem. If you have any issues, command will print them.
> 
> ```
> curl -i -X POST https://graph.facebook.com/v16.0/{phone number id}/register -H 'Authorization: Bearer {your token}' -H 'Content-Type: application/json' -d '{ "pin": "{you make up 6 digit pin}", "messaging_product": "whatsapp"}'
> ```
> 
> Maybe this link will be useful if you are building simple whatsapp integration: https://developers.facebook.com/docs/whatsapp/cloud-api/get-started-for-bsps#subscribe-waba

I tried this one but only returns

`{
    "success": true
}`

Is api changed or i made some mistake?

**Comment by ataknakbulut** [comment]
> @ataknakbulut That means it worked.

But still i can't download certificate.

**Comment by thelinuxkid** [comment]
@ataknakbulut the process will allow to change the name, not download the certificate.

**Comment by Git-Sagar-J** [comment]
> @ataknakbulut the process will allow to change the name, not download the certificate.



> > This is how I overcame this problem. If you have any issues, command will print them.
> > ```
> > curl -i -X POST https://graph.facebook.com/v16.0/{phone number id}/register -H 'Authorization: Bearer {your token}' -H 'Content-Type: application/json' -d '{ "pin": "{you make up 6 digit pin}", "messaging_product": "whatsapp"}'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Maybe this link will be useful if you are building simple whatsapp integration: https://developers.facebook.com/docs/whatsapp/cloud-api/get-started-for-bsps#subscribe-waba
> 
> This worked. Thanks!! If you turn off 2FA then follow this to turn it on again, the display name on the phone number will be changed to whatever you attempted to change it to without having to download any certificates.

i did the same but display name didn't change

**Comment by alilibx** [comment]
Hi All, 

Call This api 
`https://graph.facebook.com/v19.0/{{WABA-ID}}/phone_numbers?fields=display_phone_number,name_status,certificate,new_certificate,new_name_status
`

See below link for more infor 
https://developers.facebook.com/docs/whatsapp/embedded-signup/faq/#faq_842061566349538

**Comment by Lucisano** [comment]
FULL SOLUTION - Correct as of 09/05/2024

I have managed to verify my number and also move it from `Pending` to `Connected` without having to download the cert

1: Get your Phone Number ID

**Please ENSURE you're using the correct WABA-ID (the one your phone number is registered on, not your test account ID)**
> https://github.com/WhatsApp/WhatsApp-Business-API-Setup-Scripts/issues/59#issuecomment-2053569060
> 
> `https://graph.facebook.com/v19.0/{{WABA-ID}}/phone_numbers` 

2. Request Verification Code

> `POST 'https://graph.facebook.com/v19.0/{{PHONE-NUMBER-ID}/request_code?ode_method=VOICE&language=en'` 
> https://developers.facebook.com/docs/whatsapp/solution-providers/phone-numbers/registering-phone-numbers/

3. Verify using the Code (received above) 

> `POST https://graph.facebook.com/v19.0/{{PHONE-NUMBER-ID}}/verify_code?code={{VERIFY-CODE}}`
> https://developers.facebook.com/docs/whatsapp/solution-providers/phone-numbers/registering-phone-numbers/

4. FINALLY - Register the Phone number
I know this sounds back to front, but this is the last step to set the number as `Connected`

> `POST https://graph.facebook.com/v19.0/{{PHONE-NUMBER-ID}}/register`
> `BODY { "pin": "{{make a 6 digit pin to go here}}", "messaging_product": "whatsapp"}`

![image](https://github.com/WhatsApp/WhatsApp-Business-API-Setup-Scripts/assets/32523450/beaeab47-793f-4ec3-9709-c71be19e45b0)

**Comment by TheGlauberr** [comment]
hi @Lucisano 

where do you get the bearer token to hit the  https://graph.facebook.com/v19.0/{{WABA-ID}}/phone_numbers ?

**Comment by Lucisano** [comment]
> hi @Lucisano
> 
> where do you get the bearer token to hit the [https://graph.facebook.com/v19.0/{{WABA-ID}}/phone_numbers](https://graph.facebook.com/v19.0/%7B%7BWABA-ID%7D%7D/phone_numbers) ?

Hey @TheGlauberr 

You're best follow these docs to get a Bearer token

https://developers.facebook.com/docs/whatsapp/business-management-api/get-started#1--acquire-an-access-token-using-a-system-user-or-facebook-login

You can get a Temp token via the Quickstart Section in your App page or a Permanent Token by creating a system token

**Comment by wuler2024** [comment]
Hello guys, 

I've followed the steps provided by you to set the phone number as Connected status, and it worked. Thank you very much.

After the phone number was set to connected status, I've tried to send out a message by using API (https://graph.facebook.com/v19.0/{phone number id}/messages), it worked as well.

But now I couldn't select the phone number(in Connected status) from the Setup API page, and "You have 0 production numbers and 1 test number" appeared on the Configuration page as well. 

I would be grateful if you could tell me how to add the phone number to my app.

<img width="974" alt="1" src="https://github.com/WhatsApp/WhatsApp-Business-API-Setup-Scripts/assets/167159927/90ee35d2-a8c5-4a18-8113-e49055d89b2b">
<img width="970" alt="2" src="https://github.com/WhatsApp/WhatsApp-Business-API-Setup-Scripts/assets/167159927/956dcaea-fa92-4260-aaf7-541551f044f4">
