### ISSUE TITLE
Kubernetes manifests reference non-existent secret

### ISSUE THREAD

**Issue by nesl247** [WhatsApp/WhatsApp-Business-API-Setup-Scripts#6]
The kubernetes manifests reference a secret that isn't in the repo (`whatsapp-config`).

**Comment by thiagocmoraes** [comment]
Thanks for reporting, we will look into it.

**Comment by mengyiyuan** [comment]
@nesl247 You need to follow the guide at https://developers.facebook.com/docs/whatsapp/installation/dev-multiconnect-minikube, where it shows how the secret is created.

**Comment by nesl247** [comment]
That’s one way to do it. I would not say it’s the best way to do it. I would suggest instead to provide the secret manifest file instead, and let people fill out the values there.
