### ISSUE TITLE
ERROR: yaml.scanner.ScannerError

### ISSUE THREAD

**Issue by daemon78** [WhatsApp/WhatsApp-Business-API-Setup-Scripts#61]
ERROR: yaml.scanner.ScannerError: mapping values are not allowed here
  in "./docker-compose.yml", line 112, column 65
![yaml](https://user-images.githubusercontent.com/46240937/125959707-f359dbd6-8a5b-4b34-bd1c-23ad04676c24.JPG)

**Comment by rafaelsbatista** [comment]
@daemon78 You are using curl on the web page. You should curl the raw file instead. 

Try this:
curl -O https://raw.githubusercontent.com/WhatsApp/WhatsApp-Business-API-Setup-Scripts/master/installation/docker-compose.yml
curl -O https://raw.githubusercontent.com/WhatsApp/WhatsApp-Business-API-Setup-Scripts/master/installation/db.env
curl -O https://raw.githubusercontent.com/WhatsApp/WhatsApp-Business-API-Setup-Scripts/master/installation/multiconnect-compose.yml

**Comment by daemon78** [comment]
> @daemon78 You are using curl on the web page. You should curl the raw file instead.
> 
> Try this:
> curl -O https://raw.githubusercontent.com/WhatsApp/WhatsApp-Business-API-Setup-Scripts/master/installation/docker-compose.yml
> curl -O https://raw.githubusercontent.com/WhatsApp/WhatsApp-Business-API-Setup-Scripts/master/installation/db.env
> curl -O https://raw.githubusercontent.com/WhatsApp/WhatsApp-Business-API-Setup-Scripts/master/installation/multiconnect-compose.yml

It works fine. Thank you, its my fault
