### ISSUE TITLE
Documentation does not mention kubernetes setup

### ISSUE THREAD

**Issue by nesl247** [WhatsApp/WhatsApp-Business-API-Setup-Scripts#7]
The documentation available at developers.facebook.com does not mention the kubernetes setup. This should be documented as well. I would imagine more people will be running this setup than the `docker-compose` setup.

**Comment by thiagocmoraes** [comment]
This is available at https://developers.facebook.com/docs/whatsapp/installation/dev-multiconnect-minikube/

**Comment by nesl247** [comment]
Shouldn't it also be made available for production? I did not even think to look at the dev documentation.

**Comment by mengyiyuan** [comment]
@nesl247 What Kubernetes framework you use in production? There're many options like EKS, GKE, or on-premise, so it makes it hard for us to decide which "production" setup to work on. Your input will be valuable.
Meanwhile, I hope you can still refer to the dev k8s docs for all the necessary configs.

**Comment by nesl247** [comment]
My suggestion would be to provide a helm chart. This would work with any setup.

**Comment by Radiergummi** [comment]
@mengyiyuan maybe it would be good to do an actual survey among WhatsApp Business customers which environment they run their containers in. We use GKE, but I'm sure there are others with different requirements. It would be really awesome to have official guidelines on cluster setup and configuration for HA - especially when running large deployments (we have ~430 numbers up at this moment).

**Comment by SinghDivneet** [comment]
is there an update on this ?

**Comment by sshishov** [comment]
Hey guys, it is very easy to create HelmChart and give it to users to use and override values. Then it will not matter where will you use this chart. Do you need any help here?

**Comment by Goodsmileduck** [comment]
yeah, I just want to comment with my git repo.
I have a few updates if anyone interested I can update it tomorrow.

**Comment by sshishov** [comment]
@Goodsmileduck thank you for git repo. If you would host the chart somewhere or move it to `helm.sh` it would be great. Currently, to use your repo, I should clone it. It eliminates the possibility to easily update the version. Maybe we can cooperate with WhatsApp people and create one fancy chart for everyone.

**Comment by Goodsmileduck** [comment]
@sshishov I can't imagine helm will approve to add my chart to their curated repo. I can try to create repo using GitHub pages to store chart versions. But from the other side, I would not trust to my repo for 100% since there no other contributors plus I added there custom post-hook job which updates admin password using prebuilt docker images with python libs. So better if you can control what is happening in the repo if you want to deploy it for many customers.

**Comment by Goodsmileduck** [comment]
@amila-fc I pushed last changes to my repo, you can try, also made helm repo using gh-pages so you can pull packages from public repo. Didn't test with external mysql well, but at least it could successfully install helm release.
