### ISSUE TITLE
How to get the URL of an image in WhatsApp Business Cloud API, while we send an image through WhatsApp

### ISSUE THREAD

**Issue by MohammedHafiz** [WhatsApp/WhatsApp-Business-API-Setup-Scripts#73]
While working on WhatsApp Business Cloud API, I have to send an Image through WhatsApp. When I send that image I am getting a response as a sha256 base64 string and an imageId. I want to retrieve back that image using these credentials. I'm getting a url when I make a get request with that image id. That URL is actually broken/invalid and I'm not getting the image back.

Response of the request is given below :

"messages": [
              {
                "from": "918******6",
                "id": "wamid.HBgMOT*********EA",
                "timestamp": "1655978686",
                "type": "image",
                "image": {
                  "mime_type": "image/jpeg",
                  "sha256": "ian**********jM4k=",
                  "id": "4**********7"
                }
              }
            ]

**Comment by mengyiyuan** [comment]
Hi,

When you first uploaded the media, you should get a media ID back. With that media ID, you can retrieve the media URL with this endpoint: https://developers.facebook.com/docs/whatsapp/cloud-api/reference/media#retrieve-media-url.

With the url, you need to use a GET request with your access token to download the media: https://developers.facebook.com/docs/whatsapp/cloud-api/reference/media#download-media.

Hope this helps!
