### ISSUE TITLE
A state that manged was in-correct related to voice message !

### ISSUE THREAD

**Issue by sujin-lifology** [WhatsApp/WhatsApp-Business-API-Setup-Scripts#74]
I want to report a bug or issue 

That I found out when I played  voice message on the mobile app doesn't set the green color off, only because I first played it on my WhatsApp for pc, then only I Found out the issue is there on my phone.. 
I like to solve it ...

**Comment by mengyiyuan** [comment]
Hi sujin-lifology,

Would you mind sharing your findings in https://www.whatsapp.com/contact/?subject=messenger? This repo is for the WA Business Platform (not the desktop app).

Thank you!
