### ISSUE TITLE
Multi-Product & Single Product Messages not supporting on Cloud API

### ISSUE THREAD

**Issue by quebic-source** [WhatsApp/WhatsApp-Business-API-Setup-Scripts#75]
Hi, I need to show products on inventory through WhatsApp bot. I am using Cloud-API, but seems cloud-api does not support for Multi-Product & Single Product Messages. but it's supported by on-prem apis.

[share-products-with-customers](https://developers.facebook.com/docs/whatsapp/guides/commerce-guides/share-products-with-customers)

Is there any way to implement this kind of feature using WhatsApp Cloud-API. 

Or if I use on-prem APIs, is there any way to set up a test app without registering/verifying the business account.

**Comment by mengyiyuan** [comment]
Hi [quebic-source](https://github.com/quebic-source),

Product messages are now available on CAPI: https://developers.facebook.com/docs/whatsapp/business-platform/changelog#product-messages. Thank you for the feedback!
