### ISSUE TITLE
version Grafana 8.3.5 vulnerable to several CVEs  

### ISSUE THREAD

**Issue by bmm-alc** [WhatsApp/WhatsApp-Business-API-Setup-Scripts#79]
Version 8.3.5 is know to have several CVE, according https://grafana.com/blog/2022/07/14/grafana-v9-0-3-8-5-9-8-4-10-and-8-3-10-released-with-high-severity-security-fix/. Could you update the grafana container with the latest 8.3.x version available (or newer if possible).

As WhatsApp provides its customized container version of grafana it must update version ASAP when a CVE is published that is known to impact the version of grafana provided. 

All grafana security post related to security can be viewed at address https://grafana.com/tags/security/

**Comment by mengyiyuan** [comment]
Hi bmm-alc,

Thanks for the feedback. We have upgraded the Grafana to 8.5.9 in [v2.43.1](https://developers.facebook.com/docs/whatsapp/on-premises/changelog#wa241), we encourage you to upgrade to this latest version.
Hope this helps!
