### ISSUE TITLE
Create a way to have SSL disabled

### ISSUE THREAD

**Issue by nesl247** [WhatsApp/WhatsApp-Business-API-Setup-Scripts#8]
We use istio that terminates SSL for us. I see that there is a `disable_ssl()` function, but no way for it to be called.

It would be great if you could please add an env var that will determine if SSL is enabled or not in the webapp.

Until this is done, I'm going to have to probably create our own container or a more complex command to call this function and restart the webserver in order to have this working.

**Comment by mengyiyuan** [comment]
@nesl247 I wonder why do you want to disable SSL, which could be a security risk?

**Comment by nesl247** [comment]
I was having issues with the load balancer and I believe it to be the self-signed cert causing issues. After about an hour I got it working. It was unrelated, hence why I closed this.

**Comment by arnold-keyvalue** [comment]
@nesl247 How did you fixed it?
